### ISSUE TITLE
Ошибка в подсветке синтаксиса

### ISSUE THREAD

**Issue by timcryt** [axelofan/kumir#1]
"Съезжает" слой, ответственный за подсветку синтаксиса, из-за чего читать код становится крайне проблематичным, исправляется вручную заменой шрифта (который указан в стиле для поля ввода, но не указан в стиле для слоя подсветки) и подбором отступов для поля ввода и слоя подсветки.

![изображение](https://user-images.githubusercontent.com/34748544/71379250-b13f4280-25db-11ea-997e-f526fe0f4b3e.png)

**Comment by axelofan** [comment]
Проблема, очевидно, в вашем браузере. Установите любой современный браузер.
![123456](https://user-images.githubusercontent.com/10812483/71417766-9672d980-2680-11ea-93c3-dc8a39e8e102.png)

**Comment by timcryt** [comment]
Браузер Firefox 71.0, новее некуда

**Comment by axelofan** [comment]
Да, Firefox действительно отдаёт параметры CSS по своему.

Поправил, насколько возможно.
