### ISSUE TITLE
Баги в коде робота

### ISSUE THREAD

**Issue by timcryt** [axelofan/kumir#2]
В файле robots.js в строке 144 должно быть 
`return robot.cells[robot.y + '_' + robot.x].isFill == fill;` 
вместо 
`return robot.cells(robot.y + '_' + robot.x).isFill == fill;`
 из-за чего функции `клетка закрашена` и `клетка чистая` не работают.
 
Также в функциях `robot.paint` и `robot.move` необходимо вынести обновление закрашенности клекток и позиции рисования соответственно за таймер, иначе свойство закрашенности просто не успевает обновитсья, и команды `клетка чистая` и `клетка закрашена` будут выдавать неверные результаты при движении робота.

Для тестирования использовался код, приложенный в файле [dfs.txt](https://github.com/axelofan/kumir/files/4000582/dfs.txt)

**Comment by axelofan** [comment]
Поправил ошибки, приложенный вами код теперь работает. Заодно поправил скролл у Firefox.

И такой нюанс, оказывается в оригинальном Кумире если у функции нет аргументов, то скобки не пишутся. То есть, правильно писать dfs без скобок. Пока что такой фичи нет.

PS Добавлю вас в collaborates, чтобы вы могли добавлять что-то по желанию.
