### ISSUE TITLE
Не работают сложные условия

### ISSUE THREAD

**Issue by gav998** [axelofan/kumir#3]
Пожалуйста, добавьте сложные условия И, ИЛИ, НЕ. 

![Условие 1](https://user-images.githubusercontent.com/60404497/103198671-ee7a9680-48f9-11eb-8d26-994b1e2953de.png)
![Условие 2](https://user-images.githubusercontent.com/60404497/103198678-f1758700-48f9-11eb-9697-344fd19f960b.png)
![Ответ](https://user-images.githubusercontent.com/60404497/103198709-0fdb8280-48fa-11eb-9270-07e72986772e.png)

**Comment by axelofan** [comment]
Составные условия работают, однако ошибка действительно возникает при записи условий в скобках. Необходимые правки внесу.

**Comment by gav998** [comment]
Пример бага 
![Пример бага](https://user-images.githubusercontent.com/60404497/103199632-4ca87900-48fc-11eb-9c20-a19ecf54d2be.png)

**Comment by axelofan** [comment]
https://github.com/axelofan/kumir/commit/76b080c1f83331fc5c9260d96f7ef44348f4f264 https://github.com/axelofan/kumir/commit/36f837200c69cae28b5f0037116132e204377544

Работу со скобками поправил, дописал краткую справку по редактированию поля.
